### ISSUE TITLE
How to calculate PSNR

### ISSUE THREAD

**Issue by dummerchen** [lilygeorgescu/MHCA#4]
I've got the correct result and it works great. But because it's pixel value is not in 0~255, I don't know how to calculate psnr. 

Is it correct that I use the following code to calculate PSNR ？
```
from skimage.metrics import peak_signal_noise_ratio
psnr=peak_signal_noise_ratio(gt, pred, data_range=gt.max())
```

**Comment by lilygeorgescu** [comment]
Hi,

Your snippet code to compute the psnr is almost correct, meaning that the data_range must be equal to the distance between minimum and maximum possible values, so if the minimum value is 0 then you snippet code is correct.

In order to compute the PSNR and SSIM in our paper, we received the evaluation code from reference [50](Xiaole Zhao) where the psnr range is computed based on the whole 3D volume.

Best,
Lili
