### ISSUE TITLE
issues regarding the PSNR metric

### ISSUE THREAD

**Issue by Primer-Fan** [lilygeorgescu/MHCA#7]
Hello, there are some issues regarding the PSNR metric in the paper. This is because the dataset preprocessing and test set partitioning methods were different. The metrics I obtained are much lower than those reported in the paper. I would like to inquire about how the author preprocessed the data for the IXI dataset and how the test set was divided.

**Comment by lilygeorgescu** [comment]
Hi, 

We use the same data set settings as Zhao et al. and Zhang et al. ([49, 50] in the paper). We also use the same evaluation protocol as [49, 50], we contacted the authors of [49] and they sent us their evaluation code since we also did not match their numbers, however, with their preprocessing we were able to match their numbers.

I am not sure if I am allowed to send you their code, since it is not publicly available, however, the authors of 49 were very responsive and helpful, you can ask them to send you their evaluation code, otherwise I can briefly explain to you what they did since it s just a small preprocessing step in the computation of PSNR. 

This is taken from [49]:
"The processed datasets are available at: https://pan.baidu.com/s/1Ak3GiJk5H1Pdn3igzElb7w (kn3d)".
Please download the data set split provided by the aforementioned authors.

Best,
Lili

**Comment by nianliu26** [comment]
> Hi,
> 
> We use the same data set settings as Zhao et al. and Zhang et al. ([49, 50] in the paper). We also use the same evaluation protocol as [49, 50], we contacted the authors of [49] and they sent us their evaluation code since we also did not match their numbers, however, with their preprocessing we were able to match their numbers.
> 
> I am not sure if I am allowed to send you their code, since it is not publicly available, however, the authors of 49 were very responsive and helpful, you can ask them to send you their evaluation code, otherwise I can briefly explain to you what they did since it s just a small preprocessing step in the computation of PSNR.
> 
> This is taken from [49]: "The processed datasets are available at: https://pan.baidu.com/s/1Ak3GiJk5H1Pdn3igzElb7w (kn3d)". Please download the data set split provided by the aforementioned authors.
> 
> Best, Lili

Could you explain what they did in their method? Because I have much lower PSNR with your method
